// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/storage/dag/dag.proto

package dag

import (
	object "bonanza.build/pkg/proto/storage/object"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadDagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*UploadDagsRequest_Handshake_
	//	*UploadDagsRequest_InitiateDag_
	//	*UploadDagsRequest_ProvideObjectContents_
	Type          isUploadDagsRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDagsRequest) Reset() {
	*x = UploadDagsRequest{}
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsRequest) ProtoMessage() {}

func (x *UploadDagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsRequest.ProtoReflect.Descriptor instead.
func (*UploadDagsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{0}
}

func (x *UploadDagsRequest) GetType() isUploadDagsRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *UploadDagsRequest) GetHandshake() *UploadDagsRequest_Handshake {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsRequest_Handshake_); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *UploadDagsRequest) GetInitiateDag() *UploadDagsRequest_InitiateDag {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsRequest_InitiateDag_); ok {
			return x.InitiateDag
		}
	}
	return nil
}

func (x *UploadDagsRequest) GetProvideObjectContents() *UploadDagsRequest_ProvideObjectContents {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsRequest_ProvideObjectContents_); ok {
			return x.ProvideObjectContents
		}
	}
	return nil
}

type isUploadDagsRequest_Type interface {
	isUploadDagsRequest_Type()
}

type UploadDagsRequest_Handshake_ struct {
	Handshake *UploadDagsRequest_Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type UploadDagsRequest_InitiateDag_ struct {
	InitiateDag *UploadDagsRequest_InitiateDag `protobuf:"bytes,2,opt,name=initiate_dag,json=initiateDag,proto3,oneof"`
}

type UploadDagsRequest_ProvideObjectContents_ struct {
	ProvideObjectContents *UploadDagsRequest_ProvideObjectContents `protobuf:"bytes,3,opt,name=provide_object_contents,json=provideObjectContents,proto3,oneof"`
}

func (*UploadDagsRequest_Handshake_) isUploadDagsRequest_Type() {}

func (*UploadDagsRequest_InitiateDag_) isUploadDagsRequest_Type() {}

func (*UploadDagsRequest_ProvideObjectContents_) isUploadDagsRequest_Type() {}

type UploadDagsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*UploadDagsResponse_Handshake_
	//	*UploadDagsResponse_RequestObject_
	//	*UploadDagsResponse_FinalizeDag_
	Type          isUploadDagsResponse_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDagsResponse) Reset() {
	*x = UploadDagsResponse{}
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsResponse) ProtoMessage() {}

func (x *UploadDagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsResponse.ProtoReflect.Descriptor instead.
func (*UploadDagsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{1}
}

func (x *UploadDagsResponse) GetType() isUploadDagsResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *UploadDagsResponse) GetHandshake() *UploadDagsResponse_Handshake {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsResponse_Handshake_); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *UploadDagsResponse) GetRequestObject() *UploadDagsResponse_RequestObject {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsResponse_RequestObject_); ok {
			return x.RequestObject
		}
	}
	return nil
}

func (x *UploadDagsResponse) GetFinalizeDag() *UploadDagsResponse_FinalizeDag {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsResponse_FinalizeDag_); ok {
			return x.FinalizeDag
		}
	}
	return nil
}

type isUploadDagsResponse_Type interface {
	isUploadDagsResponse_Type()
}

type UploadDagsResponse_Handshake_ struct {
	Handshake *UploadDagsResponse_Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type UploadDagsResponse_RequestObject_ struct {
	RequestObject *UploadDagsResponse_RequestObject `protobuf:"bytes,2,opt,name=request_object,json=requestObject,proto3,oneof"`
}

type UploadDagsResponse_FinalizeDag_ struct {
	FinalizeDag *UploadDagsResponse_FinalizeDag `protobuf:"bytes,3,opt,name=finalize_dag,json=finalizeDag,proto3,oneof"`
}

func (*UploadDagsResponse_Handshake_) isUploadDagsResponse_Type() {}

func (*UploadDagsResponse_RequestObject_) isUploadDagsResponse_Type() {}

func (*UploadDagsResponse_FinalizeDag_) isUploadDagsResponse_Type() {}

type UploadDagsRequest_Handshake struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Namespace                      *object.Namespace      `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	MaximumUnfinalizedParentsLimit *object.Limit          `protobuf:"bytes,2,opt,name=maximum_unfinalized_parents_limit,json=maximumUnfinalizedParentsLimit,proto3" json:"maximum_unfinalized_parents_limit,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *UploadDagsRequest_Handshake) Reset() {
	*x = UploadDagsRequest_Handshake{}
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsRequest_Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsRequest_Handshake) ProtoMessage() {}

func (x *UploadDagsRequest_Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsRequest_Handshake.ProtoReflect.Descriptor instead.
func (*UploadDagsRequest_Handshake) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UploadDagsRequest_Handshake) GetNamespace() *object.Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *UploadDagsRequest_Handshake) GetMaximumUnfinalizedParentsLimit() *object.Limit {
	if x != nil {
		return x.MaximumUnfinalizedParentsLimit
	}
	return nil
}

type UploadDagsRequest_InitiateDag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootReference []byte                 `protobuf:"bytes,1,opt,name=root_reference,json=rootReference,proto3" json:"root_reference,omitempty"`
	RootTag       *anypb.Any             `protobuf:"bytes,2,opt,name=root_tag,json=rootTag,proto3" json:"root_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDagsRequest_InitiateDag) Reset() {
	*x = UploadDagsRequest_InitiateDag{}
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsRequest_InitiateDag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsRequest_InitiateDag) ProtoMessage() {}

func (x *UploadDagsRequest_InitiateDag) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsRequest_InitiateDag.ProtoReflect.Descriptor instead.
func (*UploadDagsRequest_InitiateDag) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{0, 1}
}

func (x *UploadDagsRequest_InitiateDag) GetRootReference() []byte {
	if x != nil {
		return x.RootReference
	}
	return nil
}

func (x *UploadDagsRequest_InitiateDag) GetRootTag() *anypb.Any {
	if x != nil {
		return x.RootTag
	}
	return nil
}

type UploadDagsRequest_ProvideObjectContents struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LowestReferenceIndex uint64                 `protobuf:"varint,1,opt,name=lowest_reference_index,json=lowestReferenceIndex,proto3" json:"lowest_reference_index,omitempty"`
	ObjectContents       []byte                 `protobuf:"bytes,2,opt,name=object_contents,json=objectContents,proto3" json:"object_contents,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UploadDagsRequest_ProvideObjectContents) Reset() {
	*x = UploadDagsRequest_ProvideObjectContents{}
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsRequest_ProvideObjectContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsRequest_ProvideObjectContents) ProtoMessage() {}

func (x *UploadDagsRequest_ProvideObjectContents) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsRequest_ProvideObjectContents.ProtoReflect.Descriptor instead.
func (*UploadDagsRequest_ProvideObjectContents) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{0, 2}
}

func (x *UploadDagsRequest_ProvideObjectContents) GetLowestReferenceIndex() uint64 {
	if x != nil {
		return x.LowestReferenceIndex
	}
	return 0
}

func (x *UploadDagsRequest_ProvideObjectContents) GetObjectContents() []byte {
	if x != nil {
		return x.ObjectContents
	}
	return nil
}

type UploadDagsResponse_Handshake struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	MaximumUnfinalizedDagsCount uint32                 `protobuf:"varint,1,opt,name=maximum_unfinalized_dags_count,json=maximumUnfinalizedDagsCount,proto3" json:"maximum_unfinalized_dags_count,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UploadDagsResponse_Handshake) Reset() {
	*x = UploadDagsResponse_Handshake{}
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsResponse_Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsResponse_Handshake) ProtoMessage() {}

func (x *UploadDagsResponse_Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsResponse_Handshake.ProtoReflect.Descriptor instead.
func (*UploadDagsResponse_Handshake) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{1, 0}
}

func (x *UploadDagsResponse_Handshake) GetMaximumUnfinalizedDagsCount() uint32 {
	if x != nil {
		return x.MaximumUnfinalizedDagsCount
	}
	return 0
}

type UploadDagsResponse_RequestObject struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	LowestReferenceIndex       uint64                 `protobuf:"varint,1,opt,name=lowest_reference_index,json=lowestReferenceIndex,proto3" json:"lowest_reference_index,omitempty"`
	AdditionalReferenceIndices uint32                 `protobuf:"varint,2,opt,name=additional_reference_indices,json=additionalReferenceIndices,proto3" json:"additional_reference_indices,omitempty"`
	RequestContents            bool                   `protobuf:"varint,3,opt,name=request_contents,json=requestContents,proto3" json:"request_contents,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UploadDagsResponse_RequestObject) Reset() {
	*x = UploadDagsResponse_RequestObject{}
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsResponse_RequestObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsResponse_RequestObject) ProtoMessage() {}

func (x *UploadDagsResponse_RequestObject) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsResponse_RequestObject.ProtoReflect.Descriptor instead.
func (*UploadDagsResponse_RequestObject) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{1, 1}
}

func (x *UploadDagsResponse_RequestObject) GetLowestReferenceIndex() uint64 {
	if x != nil {
		return x.LowestReferenceIndex
	}
	return 0
}

func (x *UploadDagsResponse_RequestObject) GetAdditionalReferenceIndices() uint32 {
	if x != nil {
		return x.AdditionalReferenceIndices
	}
	return 0
}

func (x *UploadDagsResponse_RequestObject) GetRequestContents() bool {
	if x != nil {
		return x.RequestContents
	}
	return false
}

type UploadDagsResponse_FinalizeDag struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RootReferenceIndex uint64                 `protobuf:"varint,1,opt,name=root_reference_index,json=rootReferenceIndex,proto3" json:"root_reference_index,omitempty"`
	Status             *status.Status         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadDagsResponse_FinalizeDag) Reset() {
	*x = UploadDagsResponse_FinalizeDag{}
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsResponse_FinalizeDag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsResponse_FinalizeDag) ProtoMessage() {}

func (x *UploadDagsResponse_FinalizeDag) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_dag_dag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsResponse_FinalizeDag.ProtoReflect.Descriptor instead.
func (*UploadDagsResponse_FinalizeDag) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{1, 2}
}

func (x *UploadDagsResponse_FinalizeDag) GetRootReferenceIndex() uint64 {
	if x != nil {
		return x.RootReferenceIndex
	}
	return 0
}

func (x *UploadDagsResponse_FinalizeDag) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_pkg_proto_storage_dag_dag_proto protoreflect.FileDescriptor

const file_pkg_proto_storage_dag_dag_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/storage/dag/dag.proto\x12\x13bonanza.storage.dag\x1a\x19google/protobuf/any.proto\x1a\x17google/rpc/status.proto\x1a%pkg/proto/storage/object/object.proto\"\xd6\x05\n" +
	"\x11UploadDagsRequest\x12P\n" +
	"\thandshake\x18\x01 \x01(\v20.bonanza.storage.dag.UploadDagsRequest.HandshakeH\x00R\thandshake\x12W\n" +
	"\finitiate_dag\x18\x02 \x01(\v22.bonanza.storage.dag.UploadDagsRequest.InitiateDagH\x00R\vinitiateDag\x12v\n" +
	"\x17provide_object_contents\x18\x03 \x01(\v2<.bonanza.storage.dag.UploadDagsRequest.ProvideObjectContentsH\x00R\x15provideObjectContents\x1a\xb6\x01\n" +
	"\tHandshake\x12?\n" +
	"\tnamespace\x18\x01 \x01(\v2!.bonanza.storage.object.NamespaceR\tnamespace\x12h\n" +
	"!maximum_unfinalized_parents_limit\x18\x02 \x01(\v2\x1d.bonanza.storage.object.LimitR\x1emaximumUnfinalizedParentsLimit\x1ae\n" +
	"\vInitiateDag\x12%\n" +
	"\x0eroot_reference\x18\x01 \x01(\fR\rrootReference\x12/\n" +
	"\broot_tag\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\arootTag\x1av\n" +
	"\x15ProvideObjectContents\x124\n" +
	"\x16lowest_reference_index\x18\x01 \x01(\x04R\x14lowestReferenceIndex\x12'\n" +
	"\x0fobject_contents\x18\x02 \x01(\fR\x0eobjectContentsB\x06\n" +
	"\x04type\"\x9d\x05\n" +
	"\x12UploadDagsResponse\x12Q\n" +
	"\thandshake\x18\x01 \x01(\v21.bonanza.storage.dag.UploadDagsResponse.HandshakeH\x00R\thandshake\x12^\n" +
	"\x0erequest_object\x18\x02 \x01(\v25.bonanza.storage.dag.UploadDagsResponse.RequestObjectH\x00R\rrequestObject\x12X\n" +
	"\ffinalize_dag\x18\x03 \x01(\v23.bonanza.storage.dag.UploadDagsResponse.FinalizeDagH\x00R\vfinalizeDag\x1aP\n" +
	"\tHandshake\x12C\n" +
	"\x1emaximum_unfinalized_dags_count\x18\x01 \x01(\rR\x1bmaximumUnfinalizedDagsCount\x1a\xb2\x01\n" +
	"\rRequestObject\x124\n" +
	"\x16lowest_reference_index\x18\x01 \x01(\x04R\x14lowestReferenceIndex\x12@\n" +
	"\x1cadditional_reference_indices\x18\x02 \x01(\rR\x1aadditionalReferenceIndices\x12)\n" +
	"\x10request_contents\x18\x03 \x01(\bR\x0frequestContents\x1ak\n" +
	"\vFinalizeDag\x120\n" +
	"\x14root_reference_index\x18\x01 \x01(\x04R\x12rootReferenceIndex\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.google.rpc.StatusR\x06statusB\x06\n" +
	"\x04type2m\n" +
	"\bUploader\x12a\n" +
	"\n" +
	"UploadDags\x12&.bonanza.storage.dag.UploadDagsRequest\x1a'.bonanza.storage.dag.UploadDagsResponse(\x010\x01B%Z#bonanza.build/pkg/proto/storage/dagb\x06proto3"

var (
	file_pkg_proto_storage_dag_dag_proto_rawDescOnce sync.Once
	file_pkg_proto_storage_dag_dag_proto_rawDescData []byte
)

func file_pkg_proto_storage_dag_dag_proto_rawDescGZIP() []byte {
	file_pkg_proto_storage_dag_dag_proto_rawDescOnce.Do(func() {
		file_pkg_proto_storage_dag_dag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_storage_dag_dag_proto_rawDesc), len(file_pkg_proto_storage_dag_dag_proto_rawDesc)))
	})
	return file_pkg_proto_storage_dag_dag_proto_rawDescData
}

var file_pkg_proto_storage_dag_dag_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_proto_storage_dag_dag_proto_goTypes = []any{
	(*UploadDagsRequest)(nil),                       // 0: bonanza.storage.dag.UploadDagsRequest
	(*UploadDagsResponse)(nil),                      // 1: bonanza.storage.dag.UploadDagsResponse
	(*UploadDagsRequest_Handshake)(nil),             // 2: bonanza.storage.dag.UploadDagsRequest.Handshake
	(*UploadDagsRequest_InitiateDag)(nil),           // 3: bonanza.storage.dag.UploadDagsRequest.InitiateDag
	(*UploadDagsRequest_ProvideObjectContents)(nil), // 4: bonanza.storage.dag.UploadDagsRequest.ProvideObjectContents
	(*UploadDagsResponse_Handshake)(nil),            // 5: bonanza.storage.dag.UploadDagsResponse.Handshake
	(*UploadDagsResponse_RequestObject)(nil),        // 6: bonanza.storage.dag.UploadDagsResponse.RequestObject
	(*UploadDagsResponse_FinalizeDag)(nil),          // 7: bonanza.storage.dag.UploadDagsResponse.FinalizeDag
	(*object.Namespace)(nil),                        // 8: bonanza.storage.object.Namespace
	(*object.Limit)(nil),                            // 9: bonanza.storage.object.Limit
	(*anypb.Any)(nil),                               // 10: google.protobuf.Any
	(*status.Status)(nil),                           // 11: google.rpc.Status
}
var file_pkg_proto_storage_dag_dag_proto_depIdxs = []int32{
	2,  // 0: bonanza.storage.dag.UploadDagsRequest.handshake:type_name -> bonanza.storage.dag.UploadDagsRequest.Handshake
	3,  // 1: bonanza.storage.dag.UploadDagsRequest.initiate_dag:type_name -> bonanza.storage.dag.UploadDagsRequest.InitiateDag
	4,  // 2: bonanza.storage.dag.UploadDagsRequest.provide_object_contents:type_name -> bonanza.storage.dag.UploadDagsRequest.ProvideObjectContents
	5,  // 3: bonanza.storage.dag.UploadDagsResponse.handshake:type_name -> bonanza.storage.dag.UploadDagsResponse.Handshake
	6,  // 4: bonanza.storage.dag.UploadDagsResponse.request_object:type_name -> bonanza.storage.dag.UploadDagsResponse.RequestObject
	7,  // 5: bonanza.storage.dag.UploadDagsResponse.finalize_dag:type_name -> bonanza.storage.dag.UploadDagsResponse.FinalizeDag
	8,  // 6: bonanza.storage.dag.UploadDagsRequest.Handshake.namespace:type_name -> bonanza.storage.object.Namespace
	9,  // 7: bonanza.storage.dag.UploadDagsRequest.Handshake.maximum_unfinalized_parents_limit:type_name -> bonanza.storage.object.Limit
	10, // 8: bonanza.storage.dag.UploadDagsRequest.InitiateDag.root_tag:type_name -> google.protobuf.Any
	11, // 9: bonanza.storage.dag.UploadDagsResponse.FinalizeDag.status:type_name -> google.rpc.Status
	0,  // 10: bonanza.storage.dag.Uploader.UploadDags:input_type -> bonanza.storage.dag.UploadDagsRequest
	1,  // 11: bonanza.storage.dag.Uploader.UploadDags:output_type -> bonanza.storage.dag.UploadDagsResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_proto_storage_dag_dag_proto_init() }
func file_pkg_proto_storage_dag_dag_proto_init() {
	if File_pkg_proto_storage_dag_dag_proto != nil {
		return
	}
	file_pkg_proto_storage_dag_dag_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadDagsRequest_Handshake_)(nil),
		(*UploadDagsRequest_InitiateDag_)(nil),
		(*UploadDagsRequest_ProvideObjectContents_)(nil),
	}
	file_pkg_proto_storage_dag_dag_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadDagsResponse_Handshake_)(nil),
		(*UploadDagsResponse_RequestObject_)(nil),
		(*UploadDagsResponse_FinalizeDag_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_storage_dag_dag_proto_rawDesc), len(file_pkg_proto_storage_dag_dag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_storage_dag_dag_proto_goTypes,
		DependencyIndexes: file_pkg_proto_storage_dag_dag_proto_depIdxs,
		MessageInfos:      file_pkg_proto_storage_dag_dag_proto_msgTypes,
	}.Build()
	File_pkg_proto_storage_dag_dag_proto = out.File
	file_pkg_proto_storage_dag_dag_proto_goTypes = nil
	file_pkg_proto_storage_dag_dag_proto_depIdxs = nil
}
