// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: pkg/proto/configuration/bonanza_storage_frontend/bonanza_storage_frontend.proto

package bonanza_storage_frontend

import (
	object "bonanza.build/pkg/proto/storage/object"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                          protoimpl.MessageState                     `protogen:"open.v1"`
	Global                         *global.Configuration                      `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	GrpcServers                    []*grpc.ServerConfiguration                `protobuf:"bytes,2,rep,name=grpc_servers,json=grpcServers,proto3" json:"grpc_servers,omitempty"`
	ObjectStoreConcurrency         int64                                      `protobuf:"varint,3,opt,name=object_store_concurrency,json=objectStoreConcurrency,proto3" json:"object_store_concurrency,omitempty"`
	MaximumUnfinalizedDagsCount    uint32                                     `protobuf:"varint,4,opt,name=maximum_unfinalized_dags_count,json=maximumUnfinalizedDagsCount,proto3" json:"maximum_unfinalized_dags_count,omitempty"`
	MaximumUnfinalizedParentsLimit *object.Limit                              `protobuf:"bytes,5,opt,name=maximum_unfinalized_parents_limit,json=maximumUnfinalizedParentsLimit,proto3" json:"maximum_unfinalized_parents_limit,omitempty"`
	ShardsReplicaA                 map[string]*ApplicationConfiguration_Shard `protobuf:"bytes,6,rep,name=shards_replica_a,json=shardsReplicaA,proto3" json:"shards_replica_a,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ShardsReplicaB                 map[string]*ApplicationConfiguration_Shard `protobuf:"bytes,7,rep,name=shards_replica_b,json=shardsReplicaB,proto3" json:"shards_replica_b,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetGrpcServers() []*grpc.ServerConfiguration {
	if x != nil {
		return x.GrpcServers
	}
	return nil
}

func (x *ApplicationConfiguration) GetObjectStoreConcurrency() int64 {
	if x != nil {
		return x.ObjectStoreConcurrency
	}
	return 0
}

func (x *ApplicationConfiguration) GetMaximumUnfinalizedDagsCount() uint32 {
	if x != nil {
		return x.MaximumUnfinalizedDagsCount
	}
	return 0
}

func (x *ApplicationConfiguration) GetMaximumUnfinalizedParentsLimit() *object.Limit {
	if x != nil {
		return x.MaximumUnfinalizedParentsLimit
	}
	return nil
}

func (x *ApplicationConfiguration) GetShardsReplicaA() map[string]*ApplicationConfiguration_Shard {
	if x != nil {
		return x.ShardsReplicaA
	}
	return nil
}

func (x *ApplicationConfiguration) GetShardsReplicaB() map[string]*ApplicationConfiguration_Shard {
	if x != nil {
		return x.ShardsReplicaB
	}
	return nil
}

type ApplicationConfiguration_Shard struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Client        *grpc.ClientConfiguration `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Weight        uint32                    `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationConfiguration_Shard) Reset() {
	*x = ApplicationConfiguration_Shard{}
	mi := &file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration_Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration_Shard) ProtoMessage() {}

func (x *ApplicationConfiguration_Shard) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration_Shard.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration_Shard) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ApplicationConfiguration_Shard) GetClient() *grpc.ClientConfiguration {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *ApplicationConfiguration_Shard) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto protoreflect.FileDescriptor

const file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDesc = "" +
	"\n" +
	"Opkg/proto/configuration/bonanza_storage_frontend/bonanza_storage_frontend.proto\x12.bonanza.configuration.bonanza_storage_frontend\x1a+pkg/proto/configuration/global/global.proto\x1a'pkg/proto/configuration/grpc/grpc.proto\x1a%pkg/proto/storage/object/object.proto\"\xc6\b\n" +
	"\x18ApplicationConfiguration\x12E\n" +
	"\x06global\x18\x01 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12T\n" +
	"\fgrpc_servers\x18\x02 \x03(\v21.buildbarn.configuration.grpc.ServerConfigurationR\vgrpcServers\x128\n" +
	"\x18object_store_concurrency\x18\x03 \x01(\x03R\x16objectStoreConcurrency\x12C\n" +
	"\x1emaximum_unfinalized_dags_count\x18\x04 \x01(\rR\x1bmaximumUnfinalizedDagsCount\x12h\n" +
	"!maximum_unfinalized_parents_limit\x18\x05 \x01(\v2\x1d.bonanza.storage.object.LimitR\x1emaximumUnfinalizedParentsLimit\x12\x86\x01\n" +
	"\x10shards_replica_a\x18\x06 \x03(\v2\\.bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.ShardsReplicaAEntryR\x0eshardsReplicaA\x12\x86\x01\n" +
	"\x10shards_replica_b\x18\a \x03(\v2\\.bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.ShardsReplicaBEntryR\x0eshardsReplicaB\x1aj\n" +
	"\x05Shard\x12I\n" +
	"\x06client\x18\x01 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\x06client\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\rR\x06weight\x1a\x91\x01\n" +
	"\x13ShardsReplicaAEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12d\n" +
	"\x05value\x18\x02 \x01(\v2N.bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.ShardR\x05value:\x028\x01\x1a\x91\x01\n" +
	"\x13ShardsReplicaBEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12d\n" +
	"\x05value\x18\x02 \x01(\v2N.bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.ShardR\x05value:\x028\x01B@Z>bonanza.build/pkg/proto/configuration/bonanza_storage_frontendb\x06proto3"

var (
	file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDescData []byte
)

func file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDesc), len(file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDesc)))
	})
	return file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDescData
}

var file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil),       // 0: bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration
	(*ApplicationConfiguration_Shard)(nil), // 1: bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.Shard
	nil,                                    // 2: bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.ShardsReplicaAEntry
	nil,                                    // 3: bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.ShardsReplicaBEntry
	(*global.Configuration)(nil),           // 4: buildbarn.configuration.global.Configuration
	(*grpc.ServerConfiguration)(nil),       // 5: buildbarn.configuration.grpc.ServerConfiguration
	(*object.Limit)(nil),                   // 6: bonanza.storage.object.Limit
	(*grpc.ClientConfiguration)(nil),       // 7: buildbarn.configuration.grpc.ClientConfiguration
}
var file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_depIdxs = []int32{
	4, // 0: bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	5, // 1: bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.grpc_servers:type_name -> buildbarn.configuration.grpc.ServerConfiguration
	6, // 2: bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.maximum_unfinalized_parents_limit:type_name -> bonanza.storage.object.Limit
	2, // 3: bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.shards_replica_a:type_name -> bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.ShardsReplicaAEntry
	3, // 4: bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.shards_replica_b:type_name -> bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.ShardsReplicaBEntry
	7, // 5: bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.Shard.client:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	1, // 6: bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.ShardsReplicaAEntry.value:type_name -> bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.Shard
	1, // 7: bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.ShardsReplicaBEntry.value:type_name -> bonanza.configuration.bonanza_storage_frontend.ApplicationConfiguration.Shard
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() {
	file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_init()
}
func file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_init() {
	if File_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDesc), len(file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto = out.File
	file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_goTypes = nil
	file_pkg_proto_configuration_bonanza_storage_frontend_bonanza_storage_frontend_proto_depIdxs = nil
}
