// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/encryptedaction/encryptedaction.proto

package encryptedaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PlatformPkixPublicKey  []byte                 `protobuf:"bytes,1,opt,name=platform_pkix_public_key,json=platformPkixPublicKey,proto3" json:"platform_pkix_public_key,omitempty"`
	ClientCertificateChain [][]byte               `protobuf:"bytes,2,rep,name=client_certificate_chain,json=clientCertificateChain,proto3" json:"client_certificate_chain,omitempty"`
	Nonce                  []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AdditionalData         *Action_AdditionalData `protobuf:"bytes,4,opt,name=additional_data,json=additionalData,proto3" json:"additional_data,omitempty"`
	Ciphertext             []byte                 `protobuf:"bytes,5,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_pkg_proto_encryptedaction_encryptedaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_encryptedaction_encryptedaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_pkg_proto_encryptedaction_encryptedaction_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetPlatformPkixPublicKey() []byte {
	if x != nil {
		return x.PlatformPkixPublicKey
	}
	return nil
}

func (x *Action) GetClientCertificateChain() [][]byte {
	if x != nil {
		return x.ClientCertificateChain
	}
	return nil
}

func (x *Action) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Action) GetAdditionalData() *Action_AdditionalData {
	if x != nil {
		return x.AdditionalData
	}
	return nil
}

func (x *Action) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_proto_encryptedaction_encryptedaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_encryptedaction_encryptedaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_proto_encryptedaction_encryptedaction_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Event) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type Action_AdditionalData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StableFingerprint []byte                 `protobuf:"bytes,1,opt,name=stable_fingerprint,json=stableFingerprint,proto3" json:"stable_fingerprint,omitempty"`
	ExecutionTimeout  *durationpb.Duration   `protobuf:"bytes,2,opt,name=execution_timeout,json=executionTimeout,proto3" json:"execution_timeout,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Action_AdditionalData) Reset() {
	*x = Action_AdditionalData{}
	mi := &file_pkg_proto_encryptedaction_encryptedaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action_AdditionalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_AdditionalData) ProtoMessage() {}

func (x *Action_AdditionalData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_encryptedaction_encryptedaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_AdditionalData.ProtoReflect.Descriptor instead.
func (*Action_AdditionalData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_encryptedaction_encryptedaction_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Action_AdditionalData) GetStableFingerprint() []byte {
	if x != nil {
		return x.StableFingerprint
	}
	return nil
}

func (x *Action_AdditionalData) GetExecutionTimeout() *durationpb.Duration {
	if x != nil {
		return x.ExecutionTimeout
	}
	return nil
}

var File_pkg_proto_encryptedaction_encryptedaction_proto protoreflect.FileDescriptor

const file_pkg_proto_encryptedaction_encryptedaction_proto_rawDesc = "" +
	"\n" +
	"/pkg/proto/encryptedaction/encryptedaction.proto\x12\x17bonanza.encryptedaction\x1a\x1egoogle/protobuf/duration.proto\"\x94\x03\n" +
	"\x06Action\x127\n" +
	"\x18platform_pkix_public_key\x18\x01 \x01(\fR\x15platformPkixPublicKey\x128\n" +
	"\x18client_certificate_chain\x18\x02 \x03(\fR\x16clientCertificateChain\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12W\n" +
	"\x0fadditional_data\x18\x04 \x01(\v2..bonanza.encryptedaction.Action.AdditionalDataR\x0eadditionalData\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x05 \x01(\fR\n" +
	"ciphertext\x1a\x87\x01\n" +
	"\x0eAdditionalData\x12-\n" +
	"\x12stable_fingerprint\x18\x01 \x01(\fR\x11stableFingerprint\x12F\n" +
	"\x11execution_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x10executionTimeout\"=\n" +
	"\x05Event\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertextB)Z'bonanza.build/pkg/proto/encryptedactionb\x06proto3"

var (
	file_pkg_proto_encryptedaction_encryptedaction_proto_rawDescOnce sync.Once
	file_pkg_proto_encryptedaction_encryptedaction_proto_rawDescData []byte
)

func file_pkg_proto_encryptedaction_encryptedaction_proto_rawDescGZIP() []byte {
	file_pkg_proto_encryptedaction_encryptedaction_proto_rawDescOnce.Do(func() {
		file_pkg_proto_encryptedaction_encryptedaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_encryptedaction_encryptedaction_proto_rawDesc), len(file_pkg_proto_encryptedaction_encryptedaction_proto_rawDesc)))
	})
	return file_pkg_proto_encryptedaction_encryptedaction_proto_rawDescData
}

var file_pkg_proto_encryptedaction_encryptedaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_encryptedaction_encryptedaction_proto_goTypes = []any{
	(*Action)(nil),                // 0: bonanza.encryptedaction.Action
	(*Event)(nil),                 // 1: bonanza.encryptedaction.Event
	(*Action_AdditionalData)(nil), // 2: bonanza.encryptedaction.Action.AdditionalData
	(*durationpb.Duration)(nil),   // 3: google.protobuf.Duration
}
var file_pkg_proto_encryptedaction_encryptedaction_proto_depIdxs = []int32{
	2, // 0: bonanza.encryptedaction.Action.additional_data:type_name -> bonanza.encryptedaction.Action.AdditionalData
	3, // 1: bonanza.encryptedaction.Action.AdditionalData.execution_timeout:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_encryptedaction_encryptedaction_proto_init() }
func file_pkg_proto_encryptedaction_encryptedaction_proto_init() {
	if File_pkg_proto_encryptedaction_encryptedaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_encryptedaction_encryptedaction_proto_rawDesc), len(file_pkg_proto_encryptedaction_encryptedaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_encryptedaction_encryptedaction_proto_goTypes,
		DependencyIndexes: file_pkg_proto_encryptedaction_encryptedaction_proto_depIdxs,
		MessageInfos:      file_pkg_proto_encryptedaction_encryptedaction_proto_msgTypes,
	}.Build()
	File_pkg_proto_encryptedaction_encryptedaction_proto = out.File
	file_pkg_proto_encryptedaction_encryptedaction_proto_goTypes = nil
	file_pkg_proto_encryptedaction_encryptedaction_proto_depIdxs = nil
}
