// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: pkg/proto/model/core/core.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Format:
	//
	//	*ObjectFormat_Raw
	//	*ObjectFormat_ProtoTypeName
	//	*ObjectFormat_ProtoListTypeName
	Format        isObjectFormat_Format `protobuf_oneof:"format"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectFormat) Reset() {
	*x = ObjectFormat{}
	mi := &file_pkg_proto_model_core_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectFormat) ProtoMessage() {}

func (x *ObjectFormat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_model_core_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectFormat.ProtoReflect.Descriptor instead.
func (*ObjectFormat) Descriptor() ([]byte, []int) {
	return file_pkg_proto_model_core_core_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectFormat) GetFormat() isObjectFormat_Format {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *ObjectFormat) GetRaw() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Format.(*ObjectFormat_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *ObjectFormat) GetProtoTypeName() string {
	if x != nil {
		if x, ok := x.Format.(*ObjectFormat_ProtoTypeName); ok {
			return x.ProtoTypeName
		}
	}
	return ""
}

func (x *ObjectFormat) GetProtoListTypeName() string {
	if x != nil {
		if x, ok := x.Format.(*ObjectFormat_ProtoListTypeName); ok {
			return x.ProtoListTypeName
		}
	}
	return ""
}

type isObjectFormat_Format interface {
	isObjectFormat_Format()
}

type ObjectFormat_Raw struct {
	Raw *emptypb.Empty `protobuf:"bytes,1,opt,name=raw,proto3,oneof"`
}

type ObjectFormat_ProtoTypeName struct {
	ProtoTypeName string `protobuf:"bytes,2,opt,name=proto_type_name,json=protoTypeName,proto3,oneof"`
}

type ObjectFormat_ProtoListTypeName struct {
	ProtoListTypeName string `protobuf:"bytes,3,opt,name=proto_list_type_name,json=protoListTypeName,proto3,oneof"`
}

func (*ObjectFormat_Raw) isObjectFormat_Format() {}

func (*ObjectFormat_ProtoTypeName) isObjectFormat_Format() {}

func (*ObjectFormat_ProtoListTypeName) isObjectFormat_Format() {}

type Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"fixed32,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_pkg_proto_model_core_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_model_core_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_pkg_proto_model_core_core_proto_rawDescGZIP(), []int{1}
}

func (x *Reference) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type DecodableReference struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Reference          *Reference             `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	DecodingParameters []byte                 `protobuf:"bytes,2,opt,name=decoding_parameters,json=decodingParameters,proto3" json:"decoding_parameters,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DecodableReference) Reset() {
	*x = DecodableReference{}
	mi := &file_pkg_proto_model_core_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodableReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodableReference) ProtoMessage() {}

func (x *DecodableReference) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_model_core_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodableReference.ProtoReflect.Descriptor instead.
func (*DecodableReference) Descriptor() ([]byte, []int) {
	return file_pkg_proto_model_core_core_proto_rawDescGZIP(), []int{2}
}

func (x *DecodableReference) GetReference() *Reference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *DecodableReference) GetDecodingParameters() []byte {
	if x != nil {
		return x.DecodingParameters
	}
	return nil
}

type WeakDecodableReference struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Reference          []byte                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	DecodingParameters []byte                 `protobuf:"bytes,2,opt,name=decoding_parameters,json=decodingParameters,proto3" json:"decoding_parameters,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WeakDecodableReference) Reset() {
	*x = WeakDecodableReference{}
	mi := &file_pkg_proto_model_core_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeakDecodableReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeakDecodableReference) ProtoMessage() {}

func (x *WeakDecodableReference) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_model_core_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeakDecodableReference.ProtoReflect.Descriptor instead.
func (*WeakDecodableReference) Descriptor() ([]byte, []int) {
	return file_pkg_proto_model_core_core_proto_rawDescGZIP(), []int{3}
}

func (x *WeakDecodableReference) GetReference() []byte {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *WeakDecodableReference) GetDecodingParameters() []byte {
	if x != nil {
		return x.DecodingParameters
	}
	return nil
}

type ReferenceSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indices       []uint32               `protobuf:"fixed32,1,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceSet) Reset() {
	*x = ReferenceSet{}
	mi := &file_pkg_proto_model_core_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceSet) ProtoMessage() {}

func (x *ReferenceSet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_model_core_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceSet.ProtoReflect.Descriptor instead.
func (*ReferenceSet) Descriptor() ([]byte, []int) {
	return file_pkg_proto_model_core_core_proto_rawDescGZIP(), []int{4}
}

func (x *ReferenceSet) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

type Any struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *anypb.Any             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	References    *ReferenceSet          `protobuf:"bytes,2,opt,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Any) Reset() {
	*x = Any{}
	mi := &file_pkg_proto_model_core_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Any) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Any) ProtoMessage() {}

func (x *Any) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_model_core_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Any.ProtoReflect.Descriptor instead.
func (*Any) Descriptor() ([]byte, []int) {
	return file_pkg_proto_model_core_core_proto_rawDescGZIP(), []int{5}
}

func (x *Any) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Any) GetReferences() *ReferenceSet {
	if x != nil {
		return x.References
	}
	return nil
}

var file_pkg_proto_model_core_core_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ObjectFormat)(nil),
		Field:         66941,
		Name:          "bonanza.model.core.object_format",
		Tag:           "bytes,66941,opt,name=object_format",
		Filename:      "pkg/proto/model/core/core.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bonanza.model.core.ObjectFormat object_format = 66941;
	E_ObjectFormat = &file_pkg_proto_model_core_core_proto_extTypes[0]
)

var File_pkg_proto_model_core_core_proto protoreflect.FileDescriptor

const file_pkg_proto_model_core_core_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/model/core/core.proto\x12\x12bonanza.model.core\x1a\x19google/protobuf/any.proto\x1a google/protobuf/descriptor.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa1\x01\n" +
	"\fObjectFormat\x12*\n" +
	"\x03raw\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x03raw\x12(\n" +
	"\x0fproto_type_name\x18\x02 \x01(\tH\x00R\rprotoTypeName\x121\n" +
	"\x14proto_list_type_name\x18\x03 \x01(\tH\x00R\x11protoListTypeNameB\b\n" +
	"\x06format\"!\n" +
	"\tReference\x12\x14\n" +
	"\x05index\x18\x01 \x01(\aR\x05index\"\x82\x01\n" +
	"\x12DecodableReference\x12;\n" +
	"\treference\x18\x01 \x01(\v2\x1d.bonanza.model.core.ReferenceR\treference\x12/\n" +
	"\x13decoding_parameters\x18\x02 \x01(\fR\x12decodingParameters\"g\n" +
	"\x16WeakDecodableReference\x12\x1c\n" +
	"\treference\x18\x01 \x01(\fR\treference\x12/\n" +
	"\x13decoding_parameters\x18\x02 \x01(\fR\x12decodingParameters\"(\n" +
	"\fReferenceSet\x12\x18\n" +
	"\aindices\x18\x01 \x03(\aR\aindices\"s\n" +
	"\x03Any\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x05value\x12@\n" +
	"\n" +
	"references\x18\x02 \x01(\v2 .bonanza.model.core.ReferenceSetR\n" +
	"references:f\n" +
	"\robject_format\x12\x1d.google.protobuf.FieldOptions\x18\xfd\x8a\x04 \x01(\v2 .bonanza.model.core.ObjectFormatR\fobjectFormatB$Z\"bonanza.build/pkg/proto/model/coreb\x06proto3"

var (
	file_pkg_proto_model_core_core_proto_rawDescOnce sync.Once
	file_pkg_proto_model_core_core_proto_rawDescData []byte
)

func file_pkg_proto_model_core_core_proto_rawDescGZIP() []byte {
	file_pkg_proto_model_core_core_proto_rawDescOnce.Do(func() {
		file_pkg_proto_model_core_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_model_core_core_proto_rawDesc), len(file_pkg_proto_model_core_core_proto_rawDesc)))
	})
	return file_pkg_proto_model_core_core_proto_rawDescData
}

var file_pkg_proto_model_core_core_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_model_core_core_proto_goTypes = []any{
	(*ObjectFormat)(nil),              // 0: bonanza.model.core.ObjectFormat
	(*Reference)(nil),                 // 1: bonanza.model.core.Reference
	(*DecodableReference)(nil),        // 2: bonanza.model.core.DecodableReference
	(*WeakDecodableReference)(nil),    // 3: bonanza.model.core.WeakDecodableReference
	(*ReferenceSet)(nil),              // 4: bonanza.model.core.ReferenceSet
	(*Any)(nil),                       // 5: bonanza.model.core.Any
	(*emptypb.Empty)(nil),             // 6: google.protobuf.Empty
	(*anypb.Any)(nil),                 // 7: google.protobuf.Any
	(*descriptorpb.FieldOptions)(nil), // 8: google.protobuf.FieldOptions
}
var file_pkg_proto_model_core_core_proto_depIdxs = []int32{
	6, // 0: bonanza.model.core.ObjectFormat.raw:type_name -> google.protobuf.Empty
	1, // 1: bonanza.model.core.DecodableReference.reference:type_name -> bonanza.model.core.Reference
	7, // 2: bonanza.model.core.Any.value:type_name -> google.protobuf.Any
	4, // 3: bonanza.model.core.Any.references:type_name -> bonanza.model.core.ReferenceSet
	8, // 4: bonanza.model.core.object_format:extendee -> google.protobuf.FieldOptions
	0, // 5: bonanza.model.core.object_format:type_name -> bonanza.model.core.ObjectFormat
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	5, // [5:6] is the sub-list for extension type_name
	4, // [4:5] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_model_core_core_proto_init() }
func file_pkg_proto_model_core_core_proto_init() {
	if File_pkg_proto_model_core_core_proto != nil {
		return
	}
	file_pkg_proto_model_core_core_proto_msgTypes[0].OneofWrappers = []any{
		(*ObjectFormat_Raw)(nil),
		(*ObjectFormat_ProtoTypeName)(nil),
		(*ObjectFormat_ProtoListTypeName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_model_core_core_proto_rawDesc), len(file_pkg_proto_model_core_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_model_core_core_proto_goTypes,
		DependencyIndexes: file_pkg_proto_model_core_core_proto_depIdxs,
		MessageInfos:      file_pkg_proto_model_core_core_proto_msgTypes,
		ExtensionInfos:    file_pkg_proto_model_core_core_proto_extTypes,
	}.Build()
	File_pkg_proto_model_core_core_proto = out.File
	file_pkg_proto_model_core_core_proto_goTypes = nil
	file_pkg_proto_model_core_core_proto_depIdxs = nil
}
