// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/storage/object/local/local.proto

package local

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EpochState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HashSeed         uint64                 `protobuf:"fixed64,1,opt,name=hash_seed,json=hashSeed,proto3" json:"hash_seed,omitempty"`
	LocationIncrease uint64                 `protobuf:"varint,2,opt,name=location_increase,json=locationIncrease,proto3" json:"location_increase,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EpochState) Reset() {
	*x = EpochState{}
	mi := &file_pkg_proto_storage_object_local_local_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochState) ProtoMessage() {}

func (x *EpochState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_object_local_local_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochState.ProtoReflect.Descriptor instead.
func (*EpochState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_object_local_local_proto_rawDescGZIP(), []int{0}
}

func (x *EpochState) GetHashSeed() uint64 {
	if x != nil {
		return x.HashSeed
	}
	return 0
}

func (x *EpochState) GetLocationIncrease() uint64 {
	if x != nil {
		return x.LocationIncrease
	}
	return 0
}

type PersistentState struct {
	state                                  protoimpl.MessageState `protogen:"open.v1"`
	MinimumEpochId                         uint32                 `protobuf:"varint,1,opt,name=minimum_epoch_id,json=minimumEpochId,proto3" json:"minimum_epoch_id,omitempty"`
	MinimumLocation                        uint64                 `protobuf:"varint,2,opt,name=minimum_location,json=minimumLocation,proto3" json:"minimum_location,omitempty"`
	ReferenceLocationMapHashInitialization uint64                 `protobuf:"varint,3,opt,name=reference_location_map_hash_initialization,json=referenceLocationMapHashInitialization,proto3" json:"reference_location_map_hash_initialization,omitempty"`
	Epochs                                 []*EpochState          `protobuf:"bytes,4,rep,name=epochs,proto3" json:"epochs,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *PersistentState) Reset() {
	*x = PersistentState{}
	mi := &file_pkg_proto_storage_object_local_local_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistentState) ProtoMessage() {}

func (x *PersistentState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_object_local_local_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistentState.ProtoReflect.Descriptor instead.
func (*PersistentState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_object_local_local_proto_rawDescGZIP(), []int{1}
}

func (x *PersistentState) GetMinimumEpochId() uint32 {
	if x != nil {
		return x.MinimumEpochId
	}
	return 0
}

func (x *PersistentState) GetMinimumLocation() uint64 {
	if x != nil {
		return x.MinimumLocation
	}
	return 0
}

func (x *PersistentState) GetReferenceLocationMapHashInitialization() uint64 {
	if x != nil {
		return x.ReferenceLocationMapHashInitialization
	}
	return 0
}

func (x *PersistentState) GetEpochs() []*EpochState {
	if x != nil {
		return x.Epochs
	}
	return nil
}

var File_pkg_proto_storage_object_local_local_proto protoreflect.FileDescriptor

const file_pkg_proto_storage_object_local_local_proto_rawDesc = "" +
	"\n" +
	"*pkg/proto/storage/object/local/local.proto\x12\x1cbonanza.storage.object.local\"V\n" +
	"\n" +
	"EpochState\x12\x1b\n" +
	"\thash_seed\x18\x01 \x01(\x06R\bhashSeed\x12+\n" +
	"\x11location_increase\x18\x02 \x01(\x04R\x10locationIncrease\"\x84\x02\n" +
	"\x0fPersistentState\x12(\n" +
	"\x10minimum_epoch_id\x18\x01 \x01(\rR\x0eminimumEpochId\x12)\n" +
	"\x10minimum_location\x18\x02 \x01(\x04R\x0fminimumLocation\x12Z\n" +
	"*reference_location_map_hash_initialization\x18\x03 \x01(\x04R&referenceLocationMapHashInitialization\x12@\n" +
	"\x06epochs\x18\x04 \x03(\v2(.bonanza.storage.object.local.EpochStateR\x06epochsB.Z,bonanza.build/pkg/proto/storage/object/localb\x06proto3"

var (
	file_pkg_proto_storage_object_local_local_proto_rawDescOnce sync.Once
	file_pkg_proto_storage_object_local_local_proto_rawDescData []byte
)

func file_pkg_proto_storage_object_local_local_proto_rawDescGZIP() []byte {
	file_pkg_proto_storage_object_local_local_proto_rawDescOnce.Do(func() {
		file_pkg_proto_storage_object_local_local_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_storage_object_local_local_proto_rawDesc), len(file_pkg_proto_storage_object_local_local_proto_rawDesc)))
	})
	return file_pkg_proto_storage_object_local_local_proto_rawDescData
}

var file_pkg_proto_storage_object_local_local_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_storage_object_local_local_proto_goTypes = []any{
	(*EpochState)(nil),      // 0: bonanza.storage.object.local.EpochState
	(*PersistentState)(nil), // 1: bonanza.storage.object.local.PersistentState
}
var file_pkg_proto_storage_object_local_local_proto_depIdxs = []int32{
	0, // 0: bonanza.storage.object.local.PersistentState.epochs:type_name -> bonanza.storage.object.local.EpochState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_storage_object_local_local_proto_init() }
func file_pkg_proto_storage_object_local_local_proto_init() {
	if File_pkg_proto_storage_object_local_local_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_storage_object_local_local_proto_rawDesc), len(file_pkg_proto_storage_object_local_local_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_storage_object_local_local_proto_goTypes,
		DependencyIndexes: file_pkg_proto_storage_object_local_local_proto_depIdxs,
		MessageInfos:      file_pkg_proto_storage_object_local_local_proto_msgTypes,
	}.Build()
	File_pkg_proto_storage_object_local_local_proto = out.File
	file_pkg_proto_storage_object_local_local_proto_goTypes = nil
	file_pkg_proto_storage_object_local_local_proto_depIdxs = nil
}
