// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/browser/browser.proto

package browser

import (
	encoding "bonanza.build/pkg/proto/model/encoding"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecentlyObservedEncoder struct {
	state           protoimpl.MessageState                   `protogen:"open.v1"`
	Configuration   []*encoding.BinaryEncoder                `protobuf:"bytes,1,rep,name=configuration,proto3" json:"configuration,omitempty"`
	LastObservation *RecentlyObservedEncoder_LastObservation `protobuf:"bytes,2,opt,name=last_observation,json=lastObservation,proto3" json:"last_observation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecentlyObservedEncoder) Reset() {
	*x = RecentlyObservedEncoder{}
	mi := &file_pkg_proto_browser_browser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentlyObservedEncoder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentlyObservedEncoder) ProtoMessage() {}

func (x *RecentlyObservedEncoder) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_browser_browser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentlyObservedEncoder.ProtoReflect.Descriptor instead.
func (*RecentlyObservedEncoder) Descriptor() ([]byte, []int) {
	return file_pkg_proto_browser_browser_proto_rawDescGZIP(), []int{0}
}

func (x *RecentlyObservedEncoder) GetConfiguration() []*encoding.BinaryEncoder {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *RecentlyObservedEncoder) GetLastObservation() *RecentlyObservedEncoder_LastObservation {
	if x != nil {
		return x.LastObservation
	}
	return nil
}

type Cookie struct {
	state                    protoimpl.MessageState     `protogen:"open.v1"`
	RecentlyObservedEncoders []*RecentlyObservedEncoder `protobuf:"bytes,1,rep,name=recently_observed_encoders,json=recentlyObservedEncoders,proto3" json:"recently_observed_encoders,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Cookie) Reset() {
	*x = Cookie{}
	mi := &file_pkg_proto_browser_browser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cookie) ProtoMessage() {}

func (x *Cookie) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_browser_browser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cookie.ProtoReflect.Descriptor instead.
func (*Cookie) Descriptor() ([]byte, []int) {
	return file_pkg_proto_browser_browser_proto_rawDescGZIP(), []int{1}
}

func (x *Cookie) GetRecentlyObservedEncoders() []*RecentlyObservedEncoder {
	if x != nil {
		return x.RecentlyObservedEncoders
	}
	return nil
}

type RecentlyObservedEncoder_LastObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	MessageType   string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	FieldName     string                 `protobuf:"bytes,3,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentlyObservedEncoder_LastObservation) Reset() {
	*x = RecentlyObservedEncoder_LastObservation{}
	mi := &file_pkg_proto_browser_browser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentlyObservedEncoder_LastObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentlyObservedEncoder_LastObservation) ProtoMessage() {}

func (x *RecentlyObservedEncoder_LastObservation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_browser_browser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentlyObservedEncoder_LastObservation.ProtoReflect.Descriptor instead.
func (*RecentlyObservedEncoder_LastObservation) Descriptor() ([]byte, []int) {
	return file_pkg_proto_browser_browser_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RecentlyObservedEncoder_LastObservation) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RecentlyObservedEncoder_LastObservation) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *RecentlyObservedEncoder_LastObservation) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

var File_pkg_proto_browser_browser_proto protoreflect.FileDescriptor

const file_pkg_proto_browser_browser_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/browser/browser.proto\x12\x0fbonanza.browser\x1a\x1fgoogle/protobuf/timestamp.proto\x1a'pkg/proto/model/encoding/encoding.proto\"\xd1\x02\n" +
	"\x17RecentlyObservedEncoder\x12K\n" +
	"\rconfiguration\x18\x01 \x03(\v2%.bonanza.model.encoding.BinaryEncoderR\rconfiguration\x12c\n" +
	"\x10last_observation\x18\x02 \x01(\v28.bonanza.browser.RecentlyObservedEncoder.LastObservationR\x0flastObservation\x1a\x83\x01\n" +
	"\x0fLastObservation\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12\x1d\n" +
	"\n" +
	"field_name\x18\x03 \x01(\tR\tfieldName\"p\n" +
	"\x06Cookie\x12f\n" +
	"\x1arecently_observed_encoders\x18\x01 \x03(\v2(.bonanza.browser.RecentlyObservedEncoderR\x18recentlyObservedEncodersB!Z\x1fbonanza.build/pkg/proto/browserb\x06proto3"

var (
	file_pkg_proto_browser_browser_proto_rawDescOnce sync.Once
	file_pkg_proto_browser_browser_proto_rawDescData []byte
)

func file_pkg_proto_browser_browser_proto_rawDescGZIP() []byte {
	file_pkg_proto_browser_browser_proto_rawDescOnce.Do(func() {
		file_pkg_proto_browser_browser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_browser_browser_proto_rawDesc), len(file_pkg_proto_browser_browser_proto_rawDesc)))
	})
	return file_pkg_proto_browser_browser_proto_rawDescData
}

var file_pkg_proto_browser_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_browser_browser_proto_goTypes = []any{
	(*RecentlyObservedEncoder)(nil),                 // 0: bonanza.browser.RecentlyObservedEncoder
	(*Cookie)(nil),                                  // 1: bonanza.browser.Cookie
	(*RecentlyObservedEncoder_LastObservation)(nil), // 2: bonanza.browser.RecentlyObservedEncoder.LastObservation
	(*encoding.BinaryEncoder)(nil),                  // 3: bonanza.model.encoding.BinaryEncoder
	(*timestamppb.Timestamp)(nil),                   // 4: google.protobuf.Timestamp
}
var file_pkg_proto_browser_browser_proto_depIdxs = []int32{
	3, // 0: bonanza.browser.RecentlyObservedEncoder.configuration:type_name -> bonanza.model.encoding.BinaryEncoder
	2, // 1: bonanza.browser.RecentlyObservedEncoder.last_observation:type_name -> bonanza.browser.RecentlyObservedEncoder.LastObservation
	0, // 2: bonanza.browser.Cookie.recently_observed_encoders:type_name -> bonanza.browser.RecentlyObservedEncoder
	4, // 3: bonanza.browser.RecentlyObservedEncoder.LastObservation.time:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_browser_browser_proto_init() }
func file_pkg_proto_browser_browser_proto_init() {
	if File_pkg_proto_browser_browser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_browser_browser_proto_rawDesc), len(file_pkg_proto_browser_browser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_browser_browser_proto_goTypes,
		DependencyIndexes: file_pkg_proto_browser_browser_proto_depIdxs,
		MessageInfos:      file_pkg_proto_browser_browser_proto_msgTypes,
	}.Build()
	File_pkg_proto_browser_browser_proto = out.File
	file_pkg_proto_browser_browser_proto_goTypes = nil
	file_pkg_proto_browser_browser_proto_depIdxs = nil
}
