// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: pkg/proto/storage/tag/tag.proto

package tag

import (
	object "bonanza.build/pkg/proto/storage/object"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *object.Namespace      `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Tag           *anypb.Any             `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTagRequest) Reset() {
	*x = ResolveTagRequest{}
	mi := &file_pkg_proto_storage_tag_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTagRequest) ProtoMessage() {}

func (x *ResolveTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_tag_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTagRequest.ProtoReflect.Descriptor instead.
func (*ResolveTagRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_tag_tag_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveTagRequest) GetNamespace() *object.Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *ResolveTagRequest) GetTag() *anypb.Any {
	if x != nil {
		return x.Tag
	}
	return nil
}

type ResolveTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     []byte                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Complete      bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTagResponse) Reset() {
	*x = ResolveTagResponse{}
	mi := &file_pkg_proto_storage_tag_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTagResponse) ProtoMessage() {}

func (x *ResolveTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_tag_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTagResponse.ProtoReflect.Descriptor instead.
func (*ResolveTagResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_tag_tag_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveTagResponse) GetReference() []byte {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *ResolveTagResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

type UpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *object.Namespace      `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Tag           *anypb.Any             `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Reference     []byte                 `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	Lease         []byte                 `protobuf:"bytes,4,opt,name=lease,proto3" json:"lease,omitempty"`
	Overwrite     bool                   `protobuf:"varint,5,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_pkg_proto_storage_tag_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_storage_tag_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_storage_tag_tag_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTagRequest) GetNamespace() *object.Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *UpdateTagRequest) GetTag() *anypb.Any {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *UpdateTagRequest) GetReference() []byte {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *UpdateTagRequest) GetLease() []byte {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *UpdateTagRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

var File_pkg_proto_storage_tag_tag_proto protoreflect.FileDescriptor

const file_pkg_proto_storage_tag_tag_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/storage/tag/tag.proto\x12\x13bonanza.storage.tag\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a%pkg/proto/storage/object/object.proto\"|\n" +
	"\x11ResolveTagRequest\x12?\n" +
	"\tnamespace\x18\x01 \x01(\v2!.bonanza.storage.object.NamespaceR\tnamespace\x12&\n" +
	"\x03tag\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03tag\"N\n" +
	"\x12ResolveTagResponse\x12\x1c\n" +
	"\treference\x18\x01 \x01(\fR\treference\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\"\xcd\x01\n" +
	"\x10UpdateTagRequest\x12?\n" +
	"\tnamespace\x18\x01 \x01(\v2!.bonanza.storage.object.NamespaceR\tnamespace\x12&\n" +
	"\x03tag\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03tag\x12\x1c\n" +
	"\treference\x18\x03 \x01(\fR\treference\x12\x14\n" +
	"\x05lease\x18\x04 \x01(\fR\x05lease\x12\x1c\n" +
	"\toverwrite\x18\x05 \x01(\bR\toverwrite2i\n" +
	"\bResolver\x12]\n" +
	"\n" +
	"ResolveTag\x12&.bonanza.storage.tag.ResolveTagRequest\x1a'.bonanza.storage.tag.ResolveTagResponse2U\n" +
	"\aUpdater\x12J\n" +
	"\tUpdateTag\x12%.bonanza.storage.tag.UpdateTagRequest\x1a\x16.google.protobuf.EmptyB%Z#bonanza.build/pkg/proto/storage/tagb\x06proto3"

var (
	file_pkg_proto_storage_tag_tag_proto_rawDescOnce sync.Once
	file_pkg_proto_storage_tag_tag_proto_rawDescData []byte
)

func file_pkg_proto_storage_tag_tag_proto_rawDescGZIP() []byte {
	file_pkg_proto_storage_tag_tag_proto_rawDescOnce.Do(func() {
		file_pkg_proto_storage_tag_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_storage_tag_tag_proto_rawDesc), len(file_pkg_proto_storage_tag_tag_proto_rawDesc)))
	})
	return file_pkg_proto_storage_tag_tag_proto_rawDescData
}

var file_pkg_proto_storage_tag_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_storage_tag_tag_proto_goTypes = []any{
	(*ResolveTagRequest)(nil),  // 0: bonanza.storage.tag.ResolveTagRequest
	(*ResolveTagResponse)(nil), // 1: bonanza.storage.tag.ResolveTagResponse
	(*UpdateTagRequest)(nil),   // 2: bonanza.storage.tag.UpdateTagRequest
	(*object.Namespace)(nil),   // 3: bonanza.storage.object.Namespace
	(*anypb.Any)(nil),          // 4: google.protobuf.Any
	(*emptypb.Empty)(nil),      // 5: google.protobuf.Empty
}
var file_pkg_proto_storage_tag_tag_proto_depIdxs = []int32{
	3, // 0: bonanza.storage.tag.ResolveTagRequest.namespace:type_name -> bonanza.storage.object.Namespace
	4, // 1: bonanza.storage.tag.ResolveTagRequest.tag:type_name -> google.protobuf.Any
	3, // 2: bonanza.storage.tag.UpdateTagRequest.namespace:type_name -> bonanza.storage.object.Namespace
	4, // 3: bonanza.storage.tag.UpdateTagRequest.tag:type_name -> google.protobuf.Any
	0, // 4: bonanza.storage.tag.Resolver.ResolveTag:input_type -> bonanza.storage.tag.ResolveTagRequest
	2, // 5: bonanza.storage.tag.Updater.UpdateTag:input_type -> bonanza.storage.tag.UpdateTagRequest
	1, // 6: bonanza.storage.tag.Resolver.ResolveTag:output_type -> bonanza.storage.tag.ResolveTagResponse
	5, // 7: bonanza.storage.tag.Updater.UpdateTag:output_type -> google.protobuf.Empty
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_storage_tag_tag_proto_init() }
func file_pkg_proto_storage_tag_tag_proto_init() {
	if File_pkg_proto_storage_tag_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_storage_tag_tag_proto_rawDesc), len(file_pkg_proto_storage_tag_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_proto_storage_tag_tag_proto_goTypes,
		DependencyIndexes: file_pkg_proto_storage_tag_tag_proto_depIdxs,
		MessageInfos:      file_pkg_proto_storage_tag_tag_proto_msgTypes,
	}.Build()
	File_pkg_proto_storage_tag_tag_proto = out.File
	file_pkg_proto_storage_tag_tag_proto_goTypes = nil
	file_pkg_proto_storage_tag_tag_proto_depIdxs = nil
}
