// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/configuration/scheduler/scheduler.proto

package scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionRouterConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ActionRouterConfiguration_Simple
	Kind          isActionRouterConfiguration_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRouterConfiguration) Reset() {
	*x = ActionRouterConfiguration{}
	mi := &file_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRouterConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRouterConfiguration) ProtoMessage() {}

func (x *ActionRouterConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRouterConfiguration.ProtoReflect.Descriptor instead.
func (*ActionRouterConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_scheduler_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ActionRouterConfiguration) GetKind() isActionRouterConfiguration_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ActionRouterConfiguration) GetSimple() *SimpleActionRouterConfiguration {
	if x != nil {
		if x, ok := x.Kind.(*ActionRouterConfiguration_Simple); ok {
			return x.Simple
		}
	}
	return nil
}

type isActionRouterConfiguration_Kind interface {
	isActionRouterConfiguration_Kind()
}

type ActionRouterConfiguration_Simple struct {
	Simple *SimpleActionRouterConfiguration `protobuf:"bytes,1,opt,name=simple,proto3,oneof"`
}

func (*ActionRouterConfiguration_Simple) isActionRouterConfiguration_Kind() {}

type SimpleActionRouterConfiguration struct {
	state                    protoimpl.MessageState                 `protogen:"open.v1"`
	InvocationKeyExtractors  []*InvocationKeyExtractorConfiguration `protobuf:"bytes,1,rep,name=invocation_key_extractors,json=invocationKeyExtractors,proto3" json:"invocation_key_extractors,omitempty"`
	InitialSizeClassAnalyzer *InitialSizeClassAnalyzerConfiguration `protobuf:"bytes,2,opt,name=initial_size_class_analyzer,json=initialSizeClassAnalyzer,proto3" json:"initial_size_class_analyzer,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SimpleActionRouterConfiguration) Reset() {
	*x = SimpleActionRouterConfiguration{}
	mi := &file_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleActionRouterConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleActionRouterConfiguration) ProtoMessage() {}

func (x *SimpleActionRouterConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleActionRouterConfiguration.ProtoReflect.Descriptor instead.
func (*SimpleActionRouterConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_scheduler_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleActionRouterConfiguration) GetInvocationKeyExtractors() []*InvocationKeyExtractorConfiguration {
	if x != nil {
		return x.InvocationKeyExtractors
	}
	return nil
}

func (x *SimpleActionRouterConfiguration) GetInitialSizeClassAnalyzer() *InitialSizeClassAnalyzerConfiguration {
	if x != nil {
		return x.InitialSizeClassAnalyzer
	}
	return nil
}

type InvocationKeyExtractorConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*InvocationKeyExtractorConfiguration_AuthenticationMetadata
	Kind          isInvocationKeyExtractorConfiguration_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationKeyExtractorConfiguration) Reset() {
	*x = InvocationKeyExtractorConfiguration{}
	mi := &file_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationKeyExtractorConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationKeyExtractorConfiguration) ProtoMessage() {}

func (x *InvocationKeyExtractorConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationKeyExtractorConfiguration.ProtoReflect.Descriptor instead.
func (*InvocationKeyExtractorConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_scheduler_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *InvocationKeyExtractorConfiguration) GetKind() isInvocationKeyExtractorConfiguration_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *InvocationKeyExtractorConfiguration) GetAuthenticationMetadata() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Kind.(*InvocationKeyExtractorConfiguration_AuthenticationMetadata); ok {
			return x.AuthenticationMetadata
		}
	}
	return nil
}

type isInvocationKeyExtractorConfiguration_Kind interface {
	isInvocationKeyExtractorConfiguration_Kind()
}

type InvocationKeyExtractorConfiguration_AuthenticationMetadata struct {
	AuthenticationMetadata *emptypb.Empty `protobuf:"bytes,1,opt,name=authentication_metadata,json=authenticationMetadata,proto3,oneof"`
}

func (*InvocationKeyExtractorConfiguration_AuthenticationMetadata) isInvocationKeyExtractorConfiguration_Kind() {
}

type InitialSizeClassAnalyzerConfiguration struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MaximumExecutionTimeout *durationpb.Duration   `protobuf:"bytes,1,opt,name=maximum_execution_timeout,json=maximumExecutionTimeout,proto3" json:"maximum_execution_timeout,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *InitialSizeClassAnalyzerConfiguration) Reset() {
	*x = InitialSizeClassAnalyzerConfiguration{}
	mi := &file_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialSizeClassAnalyzerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSizeClassAnalyzerConfiguration) ProtoMessage() {}

func (x *InitialSizeClassAnalyzerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSizeClassAnalyzerConfiguration.ProtoReflect.Descriptor instead.
func (*InitialSizeClassAnalyzerConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_scheduler_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *InitialSizeClassAnalyzerConfiguration) GetMaximumExecutionTimeout() *durationpb.Duration {
	if x != nil {
		return x.MaximumExecutionTimeout
	}
	return nil
}

var File_pkg_proto_configuration_scheduler_scheduler_proto protoreflect.FileDescriptor

const file_pkg_proto_configuration_scheduler_scheduler_proto_rawDesc = "" +
	"\n" +
	"1pkg/proto/configuration/scheduler/scheduler.proto\x12\x1fbonanza.configuration.scheduler\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x7f\n" +
	"\x19ActionRouterConfiguration\x12Z\n" +
	"\x06simple\x18\x01 \x01(\v2@.bonanza.configuration.scheduler.SimpleActionRouterConfigurationH\x00R\x06simpleB\x06\n" +
	"\x04kind\"\xac\x02\n" +
	"\x1fSimpleActionRouterConfiguration\x12\x80\x01\n" +
	"\x19invocation_key_extractors\x18\x01 \x03(\v2D.bonanza.configuration.scheduler.InvocationKeyExtractorConfigurationR\x17invocationKeyExtractors\x12\x85\x01\n" +
	"\x1binitial_size_class_analyzer\x18\x02 \x01(\v2F.bonanza.configuration.scheduler.InitialSizeClassAnalyzerConfigurationR\x18initialSizeClassAnalyzer\"\x80\x01\n" +
	"#InvocationKeyExtractorConfiguration\x12Q\n" +
	"\x17authentication_metadata\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x16authenticationMetadataB\x06\n" +
	"\x04kind\"~\n" +
	"%InitialSizeClassAnalyzerConfiguration\x12U\n" +
	"\x19maximum_execution_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x17maximumExecutionTimeoutB@Z>github.com/buildbarn/bonanza/pkg/proto/configuration/schedulerb\x06proto3"

var (
	file_pkg_proto_configuration_scheduler_scheduler_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_scheduler_scheduler_proto_rawDescData []byte
)

func file_pkg_proto_configuration_scheduler_scheduler_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_scheduler_scheduler_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_scheduler_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_scheduler_scheduler_proto_rawDesc), len(file_pkg_proto_configuration_scheduler_scheduler_proto_rawDesc)))
	})
	return file_pkg_proto_configuration_scheduler_scheduler_proto_rawDescData
}

var file_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_configuration_scheduler_scheduler_proto_goTypes = []any{
	(*ActionRouterConfiguration)(nil),             // 0: bonanza.configuration.scheduler.ActionRouterConfiguration
	(*SimpleActionRouterConfiguration)(nil),       // 1: bonanza.configuration.scheduler.SimpleActionRouterConfiguration
	(*InvocationKeyExtractorConfiguration)(nil),   // 2: bonanza.configuration.scheduler.InvocationKeyExtractorConfiguration
	(*InitialSizeClassAnalyzerConfiguration)(nil), // 3: bonanza.configuration.scheduler.InitialSizeClassAnalyzerConfiguration
	(*emptypb.Empty)(nil),                         // 4: google.protobuf.Empty
	(*durationpb.Duration)(nil),                   // 5: google.protobuf.Duration
}
var file_pkg_proto_configuration_scheduler_scheduler_proto_depIdxs = []int32{
	1, // 0: bonanza.configuration.scheduler.ActionRouterConfiguration.simple:type_name -> bonanza.configuration.scheduler.SimpleActionRouterConfiguration
	2, // 1: bonanza.configuration.scheduler.SimpleActionRouterConfiguration.invocation_key_extractors:type_name -> bonanza.configuration.scheduler.InvocationKeyExtractorConfiguration
	3, // 2: bonanza.configuration.scheduler.SimpleActionRouterConfiguration.initial_size_class_analyzer:type_name -> bonanza.configuration.scheduler.InitialSizeClassAnalyzerConfiguration
	4, // 3: bonanza.configuration.scheduler.InvocationKeyExtractorConfiguration.authentication_metadata:type_name -> google.protobuf.Empty
	5, // 4: bonanza.configuration.scheduler.InitialSizeClassAnalyzerConfiguration.maximum_execution_timeout:type_name -> google.protobuf.Duration
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_scheduler_scheduler_proto_init() }
func file_pkg_proto_configuration_scheduler_scheduler_proto_init() {
	if File_pkg_proto_configuration_scheduler_scheduler_proto != nil {
		return
	}
	file_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[0].OneofWrappers = []any{
		(*ActionRouterConfiguration_Simple)(nil),
	}
	file_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[2].OneofWrappers = []any{
		(*InvocationKeyExtractorConfiguration_AuthenticationMetadata)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_scheduler_scheduler_proto_rawDesc), len(file_pkg_proto_configuration_scheduler_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_scheduler_scheduler_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_scheduler_scheduler_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_scheduler_scheduler_proto = out.File
	file_pkg_proto_configuration_scheduler_scheduler_proto_goTypes = nil
	file_pkg_proto_configuration_scheduler_scheduler_proto_depIdxs = nil
}
