// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/configuration/bonanza_worker/bonanza_worker.proto

package bonanza_worker

import (
	parser "bonanza.build/pkg/proto/configuration/model/parser"
	filesystem "github.com/buildbarn/bb-remote-execution/pkg/proto/configuration/filesystem"
	virtual "github.com/buildbarn/bb-remote-execution/pkg/proto/configuration/filesystem/virtual"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state               protoimpl.MessageState            `protogen:"open.v1"`
	Global              *global.Configuration             `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	StorageGrpcClient   *grpc.ClientConfiguration         `protobuf:"bytes,2,opt,name=storage_grpc_client,json=storageGrpcClient,proto3" json:"storage_grpc_client,omitempty"`
	SchedulerGrpcClient *grpc.ClientConfiguration         `protobuf:"bytes,3,opt,name=scheduler_grpc_client,json=schedulerGrpcClient,proto3" json:"scheduler_grpc_client,omitempty"`
	BuildDirectories    []*BuildDirectoryConfiguration    `protobuf:"bytes,4,rep,name=build_directories,json=buildDirectories,proto3" json:"build_directories,omitempty"`
	FilePool            *filesystem.FilePoolConfiguration `protobuf:"bytes,5,opt,name=file_pool,json=filePool,proto3" json:"file_pool,omitempty"`
	ParsedObjectPool    *parser.ParsedObjectPool          `protobuf:"bytes,6,opt,name=parsed_object_pool,json=parsedObjectPool,proto3" json:"parsed_object_pool,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetStorageGrpcClient() *grpc.ClientConfiguration {
	if x != nil {
		return x.StorageGrpcClient
	}
	return nil
}

func (x *ApplicationConfiguration) GetSchedulerGrpcClient() *grpc.ClientConfiguration {
	if x != nil {
		return x.SchedulerGrpcClient
	}
	return nil
}

func (x *ApplicationConfiguration) GetBuildDirectories() []*BuildDirectoryConfiguration {
	if x != nil {
		return x.BuildDirectories
	}
	return nil
}

func (x *ApplicationConfiguration) GetFilePool() *filesystem.FilePoolConfiguration {
	if x != nil {
		return x.FilePool
	}
	return nil
}

func (x *ApplicationConfiguration) GetParsedObjectPool() *parser.ParsedObjectPool {
	if x != nil {
		return x.ParsedObjectPool
	}
	return nil
}

type BuildDirectoryConfiguration struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Runners       []*RunnerConfiguration      `protobuf:"bytes,1,rep,name=runners,proto3" json:"runners,omitempty"`
	Mount         *virtual.MountConfiguration `protobuf:"bytes,2,opt,name=mount,proto3" json:"mount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildDirectoryConfiguration) Reset() {
	*x = BuildDirectoryConfiguration{}
	mi := &file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildDirectoryConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildDirectoryConfiguration) ProtoMessage() {}

func (x *BuildDirectoryConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildDirectoryConfiguration.ProtoReflect.Descriptor instead.
func (*BuildDirectoryConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescGZIP(), []int{1}
}

func (x *BuildDirectoryConfiguration) GetRunners() []*RunnerConfiguration {
	if x != nil {
		return x.Runners
	}
	return nil
}

func (x *BuildDirectoryConfiguration) GetMount() *virtual.MountConfiguration {
	if x != nil {
		return x.Mount
	}
	return nil
}

type RunnerConfiguration struct {
	state                               protoimpl.MessageState    `protogen:"open.v1"`
	Endpoint                            *grpc.ClientConfiguration `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Concurrency                         uint64                    `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	PlatformPrivateKeys                 []string                  `protobuf:"bytes,3,rep,name=platform_private_keys,json=platformPrivateKeys,proto3" json:"platform_private_keys,omitempty"`
	ClientCertificateAuthorities        string                    `protobuf:"bytes,4,opt,name=client_certificate_authorities,json=clientCertificateAuthorities,proto3" json:"client_certificate_authorities,omitempty"`
	SizeClass                           uint32                    `protobuf:"varint,5,opt,name=size_class,json=sizeClass,proto3" json:"size_class,omitempty"`
	IsLargestSizeClass                  bool                      `protobuf:"varint,6,opt,name=is_largest_size_class,json=isLargestSizeClass,proto3" json:"is_largest_size_class,omitempty"`
	ShuffleDirectoryListings            bool                      `protobuf:"varint,7,opt,name=shuffle_directory_listings,json=shuffleDirectoryListings,proto3" json:"shuffle_directory_listings,omitempty"`
	HiddenFilesPattern                  string                    `protobuf:"bytes,8,opt,name=hidden_files_pattern,json=hiddenFilesPattern,proto3" json:"hidden_files_pattern,omitempty"`
	MaximumExecutionTimeoutCompensation *durationpb.Duration      `protobuf:"bytes,9,opt,name=maximum_execution_timeout_compensation,json=maximumExecutionTimeoutCompensation,proto3" json:"maximum_execution_timeout_compensation,omitempty"`
	MaximumWritableFileUploadDelay      *durationpb.Duration      `protobuf:"bytes,10,opt,name=maximum_writable_file_upload_delay,json=maximumWritableFileUploadDelay,proto3" json:"maximum_writable_file_upload_delay,omitempty"`
	MaximumFilePoolFileCount            int64                     `protobuf:"varint,11,opt,name=maximum_file_pool_file_count,json=maximumFilePoolFileCount,proto3" json:"maximum_file_pool_file_count,omitempty"`
	MaximumFilePoolSizeBytes            int64                     `protobuf:"varint,12,opt,name=maximum_file_pool_size_bytes,json=maximumFilePoolSizeBytes,proto3" json:"maximum_file_pool_size_bytes,omitempty"`
	WorkerId                            map[string]string         `protobuf:"bytes,13,rep,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnvironmentVariables                map[string]string         `protobuf:"bytes,14,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BuildDirectoryOwnerUserId           uint32                    `protobuf:"varint,15,opt,name=build_directory_owner_user_id,json=buildDirectoryOwnerUserId,proto3" json:"build_directory_owner_user_id,omitempty"`
	BuildDirectoryOwnerGroupId          uint32                    `protobuf:"varint,16,opt,name=build_directory_owner_group_id,json=buildDirectoryOwnerGroupId,proto3" json:"build_directory_owner_group_id,omitempty"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *RunnerConfiguration) Reset() {
	*x = RunnerConfiguration{}
	mi := &file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerConfiguration) ProtoMessage() {}

func (x *RunnerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerConfiguration.ProtoReflect.Descriptor instead.
func (*RunnerConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescGZIP(), []int{2}
}

func (x *RunnerConfiguration) GetEndpoint() *grpc.ClientConfiguration {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *RunnerConfiguration) GetConcurrency() uint64 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *RunnerConfiguration) GetPlatformPrivateKeys() []string {
	if x != nil {
		return x.PlatformPrivateKeys
	}
	return nil
}

func (x *RunnerConfiguration) GetClientCertificateAuthorities() string {
	if x != nil {
		return x.ClientCertificateAuthorities
	}
	return ""
}

func (x *RunnerConfiguration) GetSizeClass() uint32 {
	if x != nil {
		return x.SizeClass
	}
	return 0
}

func (x *RunnerConfiguration) GetIsLargestSizeClass() bool {
	if x != nil {
		return x.IsLargestSizeClass
	}
	return false
}

func (x *RunnerConfiguration) GetShuffleDirectoryListings() bool {
	if x != nil {
		return x.ShuffleDirectoryListings
	}
	return false
}

func (x *RunnerConfiguration) GetHiddenFilesPattern() string {
	if x != nil {
		return x.HiddenFilesPattern
	}
	return ""
}

func (x *RunnerConfiguration) GetMaximumExecutionTimeoutCompensation() *durationpb.Duration {
	if x != nil {
		return x.MaximumExecutionTimeoutCompensation
	}
	return nil
}

func (x *RunnerConfiguration) GetMaximumWritableFileUploadDelay() *durationpb.Duration {
	if x != nil {
		return x.MaximumWritableFileUploadDelay
	}
	return nil
}

func (x *RunnerConfiguration) GetMaximumFilePoolFileCount() int64 {
	if x != nil {
		return x.MaximumFilePoolFileCount
	}
	return 0
}

func (x *RunnerConfiguration) GetMaximumFilePoolSizeBytes() int64 {
	if x != nil {
		return x.MaximumFilePoolSizeBytes
	}
	return 0
}

func (x *RunnerConfiguration) GetWorkerId() map[string]string {
	if x != nil {
		return x.WorkerId
	}
	return nil
}

func (x *RunnerConfiguration) GetEnvironmentVariables() map[string]string {
	if x != nil {
		return x.EnvironmentVariables
	}
	return nil
}

func (x *RunnerConfiguration) GetBuildDirectoryOwnerUserId() uint32 {
	if x != nil {
		return x.BuildDirectoryOwnerUserId
	}
	return 0
}

func (x *RunnerConfiguration) GetBuildDirectoryOwnerGroupId() uint32 {
	if x != nil {
		return x.BuildDirectoryOwnerGroupId
	}
	return 0
}

var File_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto protoreflect.FileDescriptor

const file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDesc = "" +
	"\n" +
	";pkg/proto/configuration/bonanza_worker/bonanza_worker.proto\x12$bonanza.configuration.bonanza_worker\x1a\x1egoogle/protobuf/duration.proto\x1a3pkg/proto/configuration/filesystem/filesystem.proto\x1a8pkg/proto/configuration/filesystem/virtual/virtual.proto\x1a+pkg/proto/configuration/global/global.proto\x1a'pkg/proto/configuration/grpc/grpc.proto\x1a1pkg/proto/configuration/model/parser/parser.proto\"\xd7\x04\n" +
	"\x18ApplicationConfiguration\x12E\n" +
	"\x06global\x18\x01 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12a\n" +
	"\x13storage_grpc_client\x18\x02 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\x11storageGrpcClient\x12e\n" +
	"\x15scheduler_grpc_client\x18\x03 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\x13schedulerGrpcClient\x12n\n" +
	"\x11build_directories\x18\x04 \x03(\v2A.bonanza.configuration.bonanza_worker.BuildDirectoryConfigurationR\x10buildDirectories\x12V\n" +
	"\tfile_pool\x18\x05 \x01(\v29.buildbarn.configuration.filesystem.FilePoolConfigurationR\bfilePool\x12b\n" +
	"\x12parsed_object_pool\x18\x06 \x01(\v24.bonanza.configuration.model.parser.ParsedObjectPoolR\x10parsedObjectPool\"\xc8\x01\n" +
	"\x1bBuildDirectoryConfiguration\x12S\n" +
	"\arunners\x18\x01 \x03(\v29.bonanza.configuration.bonanza_worker.RunnerConfigurationR\arunners\x12T\n" +
	"\x05mount\x18\x02 \x01(\v2>.buildbarn.configuration.filesystem.virtual.MountConfigurationR\x05mount\"\x96\n" +
	"\n" +
	"\x13RunnerConfiguration\x12M\n" +
	"\bendpoint\x18\x01 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\bendpoint\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\x04R\vconcurrency\x122\n" +
	"\x15platform_private_keys\x18\x03 \x03(\tR\x13platformPrivateKeys\x12D\n" +
	"\x1eclient_certificate_authorities\x18\x04 \x01(\tR\x1cclientCertificateAuthorities\x12\x1d\n" +
	"\n" +
	"size_class\x18\x05 \x01(\rR\tsizeClass\x121\n" +
	"\x15is_largest_size_class\x18\x06 \x01(\bR\x12isLargestSizeClass\x12<\n" +
	"\x1ashuffle_directory_listings\x18\a \x01(\bR\x18shuffleDirectoryListings\x120\n" +
	"\x14hidden_files_pattern\x18\b \x01(\tR\x12hiddenFilesPattern\x12n\n" +
	"&maximum_execution_timeout_compensation\x18\t \x01(\v2\x19.google.protobuf.DurationR#maximumExecutionTimeoutCompensation\x12e\n" +
	"\"maximum_writable_file_upload_delay\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\x1emaximumWritableFileUploadDelay\x12>\n" +
	"\x1cmaximum_file_pool_file_count\x18\v \x01(\x03R\x18maximumFilePoolFileCount\x12>\n" +
	"\x1cmaximum_file_pool_size_bytes\x18\f \x01(\x03R\x18maximumFilePoolSizeBytes\x12d\n" +
	"\tworker_id\x18\r \x03(\v2G.bonanza.configuration.bonanza_worker.RunnerConfiguration.WorkerIdEntryR\bworkerId\x12\x88\x01\n" +
	"\x15environment_variables\x18\x0e \x03(\v2S.bonanza.configuration.bonanza_worker.RunnerConfiguration.EnvironmentVariablesEntryR\x14environmentVariables\x12@\n" +
	"\x1dbuild_directory_owner_user_id\x18\x0f \x01(\rR\x19buildDirectoryOwnerUserId\x12B\n" +
	"\x1ebuild_directory_owner_group_id\x18\x10 \x01(\rR\x1abuildDirectoryOwnerGroupId\x1a;\n" +
	"\rWorkerIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aG\n" +
	"\x19EnvironmentVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B6Z4bonanza.build/pkg/proto/configuration/bonanza_workerb\x06proto3"

var (
	file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescData []byte
)

func file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDesc), len(file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDesc)))
	})
	return file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescData
}

var file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil),         // 0: bonanza.configuration.bonanza_worker.ApplicationConfiguration
	(*BuildDirectoryConfiguration)(nil),      // 1: bonanza.configuration.bonanza_worker.BuildDirectoryConfiguration
	(*RunnerConfiguration)(nil),              // 2: bonanza.configuration.bonanza_worker.RunnerConfiguration
	nil,                                      // 3: bonanza.configuration.bonanza_worker.RunnerConfiguration.WorkerIdEntry
	nil,                                      // 4: bonanza.configuration.bonanza_worker.RunnerConfiguration.EnvironmentVariablesEntry
	(*global.Configuration)(nil),             // 5: buildbarn.configuration.global.Configuration
	(*grpc.ClientConfiguration)(nil),         // 6: buildbarn.configuration.grpc.ClientConfiguration
	(*filesystem.FilePoolConfiguration)(nil), // 7: buildbarn.configuration.filesystem.FilePoolConfiguration
	(*parser.ParsedObjectPool)(nil),          // 8: bonanza.configuration.model.parser.ParsedObjectPool
	(*virtual.MountConfiguration)(nil),       // 9: buildbarn.configuration.filesystem.virtual.MountConfiguration
	(*durationpb.Duration)(nil),              // 10: google.protobuf.Duration
}
var file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_depIdxs = []int32{
	5,  // 0: bonanza.configuration.bonanza_worker.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	6,  // 1: bonanza.configuration.bonanza_worker.ApplicationConfiguration.storage_grpc_client:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	6,  // 2: bonanza.configuration.bonanza_worker.ApplicationConfiguration.scheduler_grpc_client:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	1,  // 3: bonanza.configuration.bonanza_worker.ApplicationConfiguration.build_directories:type_name -> bonanza.configuration.bonanza_worker.BuildDirectoryConfiguration
	7,  // 4: bonanza.configuration.bonanza_worker.ApplicationConfiguration.file_pool:type_name -> buildbarn.configuration.filesystem.FilePoolConfiguration
	8,  // 5: bonanza.configuration.bonanza_worker.ApplicationConfiguration.parsed_object_pool:type_name -> bonanza.configuration.model.parser.ParsedObjectPool
	2,  // 6: bonanza.configuration.bonanza_worker.BuildDirectoryConfiguration.runners:type_name -> bonanza.configuration.bonanza_worker.RunnerConfiguration
	9,  // 7: bonanza.configuration.bonanza_worker.BuildDirectoryConfiguration.mount:type_name -> buildbarn.configuration.filesystem.virtual.MountConfiguration
	6,  // 8: bonanza.configuration.bonanza_worker.RunnerConfiguration.endpoint:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	10, // 9: bonanza.configuration.bonanza_worker.RunnerConfiguration.maximum_execution_timeout_compensation:type_name -> google.protobuf.Duration
	10, // 10: bonanza.configuration.bonanza_worker.RunnerConfiguration.maximum_writable_file_upload_delay:type_name -> google.protobuf.Duration
	3,  // 11: bonanza.configuration.bonanza_worker.RunnerConfiguration.worker_id:type_name -> bonanza.configuration.bonanza_worker.RunnerConfiguration.WorkerIdEntry
	4,  // 12: bonanza.configuration.bonanza_worker.RunnerConfiguration.environment_variables:type_name -> bonanza.configuration.bonanza_worker.RunnerConfiguration.EnvironmentVariablesEntry
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_init() }
func file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_init() {
	if File_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDesc), len(file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto = out.File
	file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_goTypes = nil
	file_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_depIdxs = nil
}
