// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: pkg/proto/remoteexecution/remoteexecution.proto

package remoteexecution

import (
	encryptedaction "bonanza.build/pkg/proto/encryptedaction"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Action        *encryptedaction.Action `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Priority      int32                   `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_remoteexecution_remoteexecution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetAction() *encryptedaction.Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ExecuteRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type WaitExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitExecutionRequest) Reset() {
	*x = WaitExecutionRequest{}
	mi := &file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitExecutionRequest) ProtoMessage() {}

func (x *WaitExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitExecutionRequest.ProtoReflect.Descriptor instead.
func (*WaitExecutionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_remoteexecution_remoteexecution_proto_rawDescGZIP(), []int{1}
}

func (x *WaitExecutionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Stage:
	//
	//	*ExecuteResponse_Queued_
	//	*ExecuteResponse_Executing_
	//	*ExecuteResponse_Completed_
	Stage         isExecuteResponse_Stage `protobuf_oneof:"stage"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_remoteexecution_remoteexecution_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecuteResponse) GetStage() isExecuteResponse_Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

func (x *ExecuteResponse) GetQueued() *ExecuteResponse_Queued {
	if x != nil {
		if x, ok := x.Stage.(*ExecuteResponse_Queued_); ok {
			return x.Queued
		}
	}
	return nil
}

func (x *ExecuteResponse) GetExecuting() *ExecuteResponse_Executing {
	if x != nil {
		if x, ok := x.Stage.(*ExecuteResponse_Executing_); ok {
			return x.Executing
		}
	}
	return nil
}

func (x *ExecuteResponse) GetCompleted() *ExecuteResponse_Completed {
	if x != nil {
		if x, ok := x.Stage.(*ExecuteResponse_Completed_); ok {
			return x.Completed
		}
	}
	return nil
}

type isExecuteResponse_Stage interface {
	isExecuteResponse_Stage()
}

type ExecuteResponse_Queued_ struct {
	Queued *ExecuteResponse_Queued `protobuf:"bytes,2,opt,name=queued,proto3,oneof"`
}

type ExecuteResponse_Executing_ struct {
	Executing *ExecuteResponse_Executing `protobuf:"bytes,3,opt,name=executing,proto3,oneof"`
}

type ExecuteResponse_Completed_ struct {
	Completed *ExecuteResponse_Completed `protobuf:"bytes,4,opt,name=completed,proto3,oneof"`
}

func (*ExecuteResponse_Queued_) isExecuteResponse_Stage() {}

func (*ExecuteResponse_Executing_) isExecuteResponse_Stage() {}

func (*ExecuteResponse_Completed_) isExecuteResponse_Stage() {}

type ExecuteResponse_Queued struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse_Queued) Reset() {
	*x = ExecuteResponse_Queued{}
	mi := &file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse_Queued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse_Queued) ProtoMessage() {}

func (x *ExecuteResponse_Queued) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse_Queued.ProtoReflect.Descriptor instead.
func (*ExecuteResponse_Queued) Descriptor() ([]byte, []int) {
	return file_pkg_proto_remoteexecution_remoteexecution_proto_rawDescGZIP(), []int{2, 0}
}

type ExecuteResponse_Executing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastEvent     *encryptedaction.Event `protobuf:"bytes,1,opt,name=last_event,json=lastEvent,proto3" json:"last_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse_Executing) Reset() {
	*x = ExecuteResponse_Executing{}
	mi := &file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse_Executing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse_Executing) ProtoMessage() {}

func (x *ExecuteResponse_Executing) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse_Executing.ProtoReflect.Descriptor instead.
func (*ExecuteResponse_Executing) Descriptor() ([]byte, []int) {
	return file_pkg_proto_remoteexecution_remoteexecution_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ExecuteResponse_Executing) GetLastEvent() *encryptedaction.Event {
	if x != nil {
		return x.LastEvent
	}
	return nil
}

type ExecuteResponse_Completed struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompletionEvent *encryptedaction.Event `protobuf:"bytes,1,opt,name=completion_event,json=completionEvent,proto3" json:"completion_event,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteResponse_Completed) Reset() {
	*x = ExecuteResponse_Completed{}
	mi := &file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse_Completed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse_Completed) ProtoMessage() {}

func (x *ExecuteResponse_Completed) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse_Completed.ProtoReflect.Descriptor instead.
func (*ExecuteResponse_Completed) Descriptor() ([]byte, []int) {
	return file_pkg_proto_remoteexecution_remoteexecution_proto_rawDescGZIP(), []int{2, 2}
}

func (x *ExecuteResponse_Completed) GetCompletionEvent() *encryptedaction.Event {
	if x != nil {
		return x.CompletionEvent
	}
	return nil
}

var File_pkg_proto_remoteexecution_remoteexecution_proto protoreflect.FileDescriptor

const file_pkg_proto_remoteexecution_remoteexecution_proto_rawDesc = "" +
	"\n" +
	"/pkg/proto/remoteexecution/remoteexecution.proto\x12\x17bonanza.remoteexecution\x1a/pkg/proto/encryptedaction/encryptedaction.proto\"e\n" +
	"\x0eExecuteRequest\x127\n" +
	"\x06action\x18\x01 \x01(\v2\x1f.bonanza.encryptedaction.ActionR\x06action\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\"*\n" +
	"\x14WaitExecutionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xcf\x03\n" +
	"\x0fExecuteResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12I\n" +
	"\x06queued\x18\x02 \x01(\v2/.bonanza.remoteexecution.ExecuteResponse.QueuedH\x00R\x06queued\x12R\n" +
	"\texecuting\x18\x03 \x01(\v22.bonanza.remoteexecution.ExecuteResponse.ExecutingH\x00R\texecuting\x12R\n" +
	"\tcompleted\x18\x04 \x01(\v22.bonanza.remoteexecution.ExecuteResponse.CompletedH\x00R\tcompleted\x1a\b\n" +
	"\x06Queued\x1aJ\n" +
	"\tExecuting\x12=\n" +
	"\n" +
	"last_event\x18\x01 \x01(\v2\x1e.bonanza.encryptedaction.EventR\tlastEvent\x1aV\n" +
	"\tCompleted\x12I\n" +
	"\x10completion_event\x18\x01 \x01(\v2\x1e.bonanza.encryptedaction.EventR\x0fcompletionEventB\a\n" +
	"\x05stage2\xd7\x01\n" +
	"\tExecution\x12^\n" +
	"\aExecute\x12'.bonanza.remoteexecution.ExecuteRequest\x1a(.bonanza.remoteexecution.ExecuteResponse0\x01\x12j\n" +
	"\rWaitExecution\x12-.bonanza.remoteexecution.WaitExecutionRequest\x1a(.bonanza.remoteexecution.ExecuteResponse0\x01B)Z'bonanza.build/pkg/proto/remoteexecutionb\x06proto3"

var (
	file_pkg_proto_remoteexecution_remoteexecution_proto_rawDescOnce sync.Once
	file_pkg_proto_remoteexecution_remoteexecution_proto_rawDescData []byte
)

func file_pkg_proto_remoteexecution_remoteexecution_proto_rawDescGZIP() []byte {
	file_pkg_proto_remoteexecution_remoteexecution_proto_rawDescOnce.Do(func() {
		file_pkg_proto_remoteexecution_remoteexecution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_remoteexecution_remoteexecution_proto_rawDesc), len(file_pkg_proto_remoteexecution_remoteexecution_proto_rawDesc)))
	})
	return file_pkg_proto_remoteexecution_remoteexecution_proto_rawDescData
}

var file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_remoteexecution_remoteexecution_proto_goTypes = []any{
	(*ExecuteRequest)(nil),            // 0: bonanza.remoteexecution.ExecuteRequest
	(*WaitExecutionRequest)(nil),      // 1: bonanza.remoteexecution.WaitExecutionRequest
	(*ExecuteResponse)(nil),           // 2: bonanza.remoteexecution.ExecuteResponse
	(*ExecuteResponse_Queued)(nil),    // 3: bonanza.remoteexecution.ExecuteResponse.Queued
	(*ExecuteResponse_Executing)(nil), // 4: bonanza.remoteexecution.ExecuteResponse.Executing
	(*ExecuteResponse_Completed)(nil), // 5: bonanza.remoteexecution.ExecuteResponse.Completed
	(*encryptedaction.Action)(nil),    // 6: bonanza.encryptedaction.Action
	(*encryptedaction.Event)(nil),     // 7: bonanza.encryptedaction.Event
}
var file_pkg_proto_remoteexecution_remoteexecution_proto_depIdxs = []int32{
	6, // 0: bonanza.remoteexecution.ExecuteRequest.action:type_name -> bonanza.encryptedaction.Action
	3, // 1: bonanza.remoteexecution.ExecuteResponse.queued:type_name -> bonanza.remoteexecution.ExecuteResponse.Queued
	4, // 2: bonanza.remoteexecution.ExecuteResponse.executing:type_name -> bonanza.remoteexecution.ExecuteResponse.Executing
	5, // 3: bonanza.remoteexecution.ExecuteResponse.completed:type_name -> bonanza.remoteexecution.ExecuteResponse.Completed
	7, // 4: bonanza.remoteexecution.ExecuteResponse.Executing.last_event:type_name -> bonanza.encryptedaction.Event
	7, // 5: bonanza.remoteexecution.ExecuteResponse.Completed.completion_event:type_name -> bonanza.encryptedaction.Event
	0, // 6: bonanza.remoteexecution.Execution.Execute:input_type -> bonanza.remoteexecution.ExecuteRequest
	1, // 7: bonanza.remoteexecution.Execution.WaitExecution:input_type -> bonanza.remoteexecution.WaitExecutionRequest
	2, // 8: bonanza.remoteexecution.Execution.Execute:output_type -> bonanza.remoteexecution.ExecuteResponse
	2, // 9: bonanza.remoteexecution.Execution.WaitExecution:output_type -> bonanza.remoteexecution.ExecuteResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_proto_remoteexecution_remoteexecution_proto_init() }
func file_pkg_proto_remoteexecution_remoteexecution_proto_init() {
	if File_pkg_proto_remoteexecution_remoteexecution_proto != nil {
		return
	}
	file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecuteResponse_Queued_)(nil),
		(*ExecuteResponse_Executing_)(nil),
		(*ExecuteResponse_Completed_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_remoteexecution_remoteexecution_proto_rawDesc), len(file_pkg_proto_remoteexecution_remoteexecution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_remoteexecution_remoteexecution_proto_goTypes,
		DependencyIndexes: file_pkg_proto_remoteexecution_remoteexecution_proto_depIdxs,
		MessageInfos:      file_pkg_proto_remoteexecution_remoteexecution_proto_msgTypes,
	}.Build()
	File_pkg_proto_remoteexecution_remoteexecution_proto = out.File
	file_pkg_proto_remoteexecution_remoteexecution_proto_goTypes = nil
	file_pkg_proto_remoteexecution_remoteexecution_proto_depIdxs = nil
}
